-- PLSQL
-- Create table for Devil Fruits
CREATE TABLE devil_fruits (
    id NUMBER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    power VARCHAR2(50) NOT NULL,
    subpower VARCHAR2(50),
    description VARCHAR2(255)
);

-- Insert data into Devil Fruits table
INSERT INTO devil_fruits (power, subpower, description) VALUES 
('Devil Fruits', 'Paramecia', 'Grants unique abilities, not limited to physical transformations.'),
('Devil Fruits', 'Zoan', 'Allows the user to transform into an animal and gain its abilities.'),
('Devil Fruits', 'Logia', 'Enables the user to become a natural element and control it.'),
('Devil Fruits', 'Mythical Zoan', 'Grants the user abilities of mythical creatures like phoenixes or dragons.'),
('Devil Fruits', 'Ancient Zoan', 'Allows transformations into extinct creatures such as dinosaurs.'),
('Devil Fruits', 'Awakened Paramecia', 'Enhances the user’s abilities to influence their surroundings.'),
('Devil Fruits', 'Awakened Zoan', 'Greatly boosts the user’s physical strength and recovery rate.'),
('Devil Fruits', 'Awakened Logia', 'Allows near-total mastery of the respective natural element.'),
('Devil Fruits', 'Special Paramecia', 'Functions like a Logia but categorized as Paramecia.'),
('Devil Fruits', 'Artificial Zoan', 'Synthetic fruits created by science, such as SMILE fruits.');
('Devil Fruits', 'Elemental Paramecia', 'Paramecia fruits granting powers related to natural forces but not classified as Logia.'),
('Devil Fruits', 'Beastial Hybrid Zoan', 'Allows the user to take on combined features of multiple animals.'),
('Devil Fruits', 'Marine Zoan', 'Grants transformations into aquatic creatures while overcoming water-related weaknesses.'),
('Devil Fruits', 'Chimera Zoan', 'Provides the ability to transform into a mythical hybrid of multiple animals.'),
('Devil Fruits', 'Compound Logia', 'Grants control over multiple related natural elements, like ash and fire.'),
('Devil Fruits', 'Etherial Logia', 'Enables the user to embody intangible forces like light or shadows.'),
('Devil Fruits', 'Dual-Type Devil Fruit', 'A rare anomaly combining traits of two distinct Devil Fruit types.'),
('Devil Fruits', 'Floral Paramecia', 'Grants abilities to control or grow plants with unique properties.'),
('Devil Fruits', 'Gigantification Paramecia', 'Allows the user to alter their size, growing or shrinking at will.'),
('Devil Fruits', 'Energy Paramecia', 'Enables manipulation of raw energy forms like electricity or heat.'),
('Devil Fruits', 'Tactical Zoan', 'Grants the user forms specialized for combat and strategy.'),
('Devil Fruits', 'Hybrid Ancient Zoan', 'Enables transformations into hybrids of ancient creatures.'),
('Devil Fruits', 'Celestial Mythical Zoan', 'Grants abilities inspired by celestial beings or gods.'),
('Devil Fruits', 'Awakened Mythical Zoan', 'Greatly amplifies the mythical abilities of the user.'),
('Devil Fruits', 'Temporal Paramecia', 'Allows manipulation of time in limited ways.'),
('Devil Fruits', 'Spatial Paramecia', 'Grants control over spatial dimensions, like teleportation or portals.'),
('Devil Fruits', 'Magnetism Paramecia', 'Provides control over magnetic forces and metallic objects.'),
('Devil Fruits', 'Golem Zoan', 'Allows transformations into elemental constructs like stone or clay golems.'),
('Devil Fruits', 'Synthetic Paramecia', 'Artificial Paramecia fruits created through advanced technology.'),
('Devil Fruits', 'Energy Logia', 'Enables mastery over energy-based elements like plasma or solar rays.')
('Devil Fruits', 'Plot Paramecia', 'Grants the user godlike abilities to alter reality, control fate, and reshape the world like a black-and-white canvas. The user’s appearance resembels a fish.');

-- Create table for Haki
CREATE TABLE haki (
    id NUMBER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    power VARCHAR2(50) NOT NULL,
    subpower VARCHAR2(50),
    description VARCHAR2(255)
);

-- Insert data into Haki table
INSERT INTO haki (power, subpower, description) VALUES 
('Haki', 'Kenbunshoku Haki', 'Allows the user to sense the presence and emotions of others.'),
('Haki', 'Busoshoku Haki', 'Enables the user to create invisible armor around themselves.'),
('Haki', 'Haoshoku Haki', 'Grants the user the ability to exert their will over others.'),
('Haki', 'Advanced Kenbunshoku Haki', 'Allows the user to briefly see into the future.'),
('Haki', 'Advanced Busoshoku Haki', 'Enables emission of Haki to attack from a distance.'),
('Haki', 'Haoshoku Haki Infusion', 'Permits the user to infuse conqueror’s Haki into attacks.'),
('Haki', 'Observation Range Expansion', 'Significantly increases the range of sensing.'),
('Haki', 'Haki Endurance', 'The ability to use Haki for extended periods.');

-- Create table for Martial Arts
CREATE TABLE martial_arts (
    id NUMBER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    power VARCHAR2(50) NOT NULL,
    subpower VARCHAR2(50),
    description VARCHAR2(255)
);

-- Insert data into Martial Arts table
INSERT INTO martial_arts (power, subpower, description) VALUES 
('Martial Arts', 'Iron Body Technique', 'A defensive style that hardens the body to withstand heavy attacks.'),
('Martial Arts', 'Sky Walk', 'An acrobatic technique allowing movement through the air.'),
('Martial Arts', 'Finger Spear', 'A precision-based style using fingers as piercing weapons.'),
('Martial Arts', 'Air Slash', 'A technique that generates cutting waves of air with a weapon or motion.'),
('Martial Arts', 'Paper Art', 'A dodging style that enhances flexibility and fluid movement.'),
('Martial Arts', 'Storm Leg', 'A powerful kicking technique that creates slicing shockwaves.'),
('Martial Arts', 'Water Stream Flow', 'A flowing style focusing on redirecting the force of an opponent.'),
('Martial Arts', 'Whirlpool Strike', 'A spinning attack that generates a powerful vortex of energy.'),
('Martial Arts', 'Shatter Fist', 'A striking style that targets and breaks through defenses.'),
('Martial Arts', 'Thunder Palm', 'A palm-based technique that delivers shockwave-like impacts.'),
('Martial Arts', 'Flame Fist', 'A fiery technique that combines heat and striking force.'),
('Martial Arts', 'Crimson Wave', 'A blade-based style focusing on swift, fluid movements.'),
('Martial Arts', 'Silent Step', 'A stealth technique that enables nearly silent movements.'),
('Martial Arts', 'Shadow Fang', 'A style focused on rapid, precision strikes targeting weak points.'),
('Martial Arts', 'Stone Crusher', 'A style using overwhelming force to crush through obstacles.'),
('Martial Arts', 'Ripple Flow', 'A technique that creates waves of energy through rhythmic movements.'),
('Martial Arts', 'Heaven’s Ascent', 'An aerial combat style emphasizing acrobatics and high-speed attacks.'),
('Martial Arts', 'Storm Surge', 'A water-based style that delivers crashing, overwhelming strikes.'),
('Martial Arts', 'Blazing Edge', 'A sword-fighting technique that combines speed and fiery strikes.'),
('Martial Arts', 'Earth Shatter', 'A ground-focused style that uses stomps and shockwaves.'),
('Martial Arts', 'Ice Fang', 'A cold-focused technique delivering chilling, precise strikes.'),
('Martial Arts', 'Whirlwind Claw', 'A spinning claw technique that generates slicing winds.'),
('Martial Arts', 'Phoenix Strike', 'A fiery aerial technique that combines speed and impact.'),
('Martial Arts', 'Serpent Coil', 'A grappling style focusing on coiling and immobilizing the opponent.'),
('Martial Arts', 'Iron Grip', 'A style focused on overwhelming strength and grappling techniques.'),
('Martial Arts', 'Lightning Step', 'A high-speed movement technique leaving afterimages.'),
('Martial Arts', 'Wave Blade', 'A sword technique that delivers slashing strikes resembling ocean waves.'),
('Martial Arts', 'Moonlit Dance', 'A graceful combat style emphasizing fluid, unpredictable movements.'),
('Martial Arts', 'Meteor Kick', 'A devastating aerial kicking technique with tremendous force.'),
('Martial Arts', 'Thunder Clap', 'A hand-based style that delivers concussive, shockwave attacks.'),
('Martial Arts', 'Steel Fang', 'A biting combat style with hardened, piercing strikes.'),
('Martial Arts', 'Blade Tempest', 'A technique using rapid spinning strikes to create a storm of slashes.'),
('Martial Arts', 'Dragon Roar', 'A striking style that generates powerful shockwaves resembling a roar.'),
('Martial Arts', 'Frost Palm', 'A cold-based style delivering freezing strikes to immobilize opponents.'),
('Martial Arts', 'Solar Strike', 'A heat-based combat style combining speed and precision.'),
('Martial Arts', 'Twilight Fang', 'A balanced style blending power and speed in unison.'),
('Martial Arts', 'Iron Wave', 'A technique delivering overwhelming force like a crashing wave.'),
('Martial Arts', 'Lunar Flow', 'A calm, flowing style emphasizing defense and counterattacks.'),
('Martial Arts', 'Blizzard Blade', 'A sword technique creating icy slashes with a chilling edge.'),
('Martial Arts', 'Tempest Spin', 'A spinning attack that generates wind-based shockwaves.'),
('Martial Arts', 'Ocean Current Strike', 'A technique that mimics the force of powerful ocean currents.'),
('Martial Arts', 'Piercing Howl', 'A shockwave technique delivering sonic bursts.'),
('Martial Arts', 'Silent Edge', 'A stealthy blade style focusing on precision and surprise attacks.'),
('Martial Arts', 'Burning Spiral', 'A spinning technique that generates fiery energy for attacks.'),
('Martial Arts', 'Shocking Claw', 'A claw-based style delivering electrified strikes.'),
('Martial Arts', 'Vortex Spear', 'A spear-fighting technique creating spiraling wind attacks.'),
('Martial Arts', 'Crushing Tide', 'A water-based style using heavy, overwhelming strikes.'),
('Martial Arts', 'Storm Fist', 'A rapid, forceful punching style that mimics a thunderstorm.'),
('Martial Arts', 'Eclipse Fang', 'A shadowy style that emphasizes speed and evasion.'),
('Martial Arts', 'Sky Breaker', 'An aerial style that combines high-altitude strikes with overwhelming force.')
('Martial Arts', 'Sea Serpent Slash', 'A sword technique mimicking the unpredictable movements of a sea serpent.'),
('Martial Arts', 'Cyclone Kick', 'A spinning kick that generates powerful wind-based shockwaves.'),
('Martial Arts', 'Earthquake Fist', 'A striking style that creates tremors upon impact.'),
('Martial Arts', 'Sky Piercer', 'An aerial combat technique focused on high-altitude attacks.'),
('Martial Arts', 'Tidal Strike', 'A water-based technique that mimics the surging force of a tidal wave.'),
('Martial Arts', 'Cloud Step', 'A movement technique that allows fluid and evasive actions in midair.'),
('Martial Arts', 'Storm Fang', 'A rapid, claw-based style that generates slicing winds.'),
('Martial Arts', 'Volcanic Fist', 'A striking technique that combines intense heat with destructive power.'),
('Martial Arts', 'Frostbite Kick', 'A chilling kick-based style that freezes opponents on impact.'),
('Martial Arts', 'Whirlpool Slash', 'A blade technique that creates a spiraling vortex of energy.'),
('Martial Arts', 'Thunderbolt Palm', 'A shockwave-focused technique with electrifying force.'),
('Martial Arts', 'Glacier Claw', 'A claw-based style that delivers icy strikes, freezing targets.'),
('Martial Arts', 'Steel Cyclone', 'A spinning style that combines overwhelming force with defensive capability.'),
('Martial Arts', 'Dragon Tail Sweep', 'A sweeping attack resembling the powerful motion of a dragon’s tail.'),
('Martial Arts', 'Lightning Fang', 'A rapid claw technique infused with electrical energy.'),
('Martial Arts', 'Crimson Hurricane', 'A blade technique that generates a fiery whirlwind.'),
('Martial Arts', 'Meteor Palm', 'A striking style delivering heavy, earth-shaking impacts.'),
('Martial Arts', 'Serpent Strike', 'A swift, precise style with movements resembling a snake’s attack.'),
('Martial Arts', 'Eruption Stomp', 'A ground-based technique that creates explosive shockwaves.'),
('Martial Arts', 'Wind Razor', 'A high-speed sword style that creates sharp, slicing winds.');

-- Create table for Weather Control
CREATE TABLE weather_control (
    id NUMBER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    power VARCHAR2(50) NOT NULL,
    subpower VARCHAR2(50),
    description VARCHAR2(255)
);

-- Insert data into Weather Control table
INSERT INTO weather_control (power, subpower, description) VALUES 
('Weather Control', 'Clima-Tact', 'Weapon that manipulates weather.'),
('Weather Control', 'Thunder Lance Tempo', 'Generates a powerful lightning strike.'),
('Weather Control', 'Cyclone Burst', 'Creates a massive tornado-like attack.'),
('Weather Control', 'Mirage Tempo', 'Allows to create optical illusions with weather.');


-- Create table for Rokushiki
CREATE TABLE rokushiki (
    id NUMBER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    power VARCHAR2(50) NOT NULL,
    subpower VARCHAR2(50),
    description VARCHAR2(255)
);

-- Insert data into Rokushiki table
INSERT INTO rokushiki (power, subpower, description) VALUES 
('Rokushiki', 'Soru', 'Super speed technique.'),
('Rokushiki', 'Geppo', 'Allows the user to walk on air.'),
('Rokushiki', 'Tekkai', 'Defensive technique that hardens the body.'),
('Rokushiki', 'Shigan', 'Finger gun attack technique.'),
('Rokushiki', 'Rankyaku', 'Air blade attack.'),
('Rokushiki', 'Kami-e', 'Dodging technique through flexibility.'),
('Rokushiki', 'Rokuogan', 'A powerful energy-based finishing move.');

-- Create table for Cyborg Modifications
CREATE TABLE cyborg_modifications (
    id NUMBER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    power VARCHAR2(50) NOT NULL,
    description VARCHAR2(255)
);

-- Insert data into Cyborg Modifications table
INSERT INTO cyborg_modifications (power, description) VALUES 
('Cyborg Modifications', 'Enhancements used by Franky and Pacifistas for combat and defense.'),
('Cyborg Modifications', 'Laser Beams', 'Weaponized laser attacks.'),
('Cyborg Modifications', 'Steel Plating', 'Enhanced defense through metal plating.');

-- Create table for Giant Strength
CREATE TABLE giant_strength (
    id NUMBER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    power VARCHAR2(50) NOT NULL,
    description VARCHAR2(255)
);

-- Insert data into Giant Strength table
INSERT INTO giant_strength (power, description) VALUES 
('Giant Strength', 'Natural strength due to massive size.'),
('Giant Strength', 'Enhanced Physical Prowess', 'Allows incredible feats of power.');

-- Create table for Vinsmoke Germa Technology
CREATE TABLE vinsmoke_germa (
    id NUMBER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    power VARCHAR2(50) NOT NULL,
    description VARCHAR2(255)
);

-- Insert data into Vinsmoke Germa Technology table
INSERT INTO vinsmoke_germa (power, description) VALUES 
('Vinsmoke Germa Technology', 'Raid Suits grant superhuman abilities.'),
('Vinsmoke Germa Technology', 'Electrified Combat Suits', 'Shock-resistant armors with electric combat features.');


-- Create table for Minks' Sulong Form
CREATE TABLE minks_sulong (
    id NUMBER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    power VARCHAR2(50) NOT NULL,
    description VARCHAR2(255)
);

-- Insert data into Minks' Sulong Form table
INSERT INTO minks_sulong (power, description) VALUES 
('Minks'' Sulong Form', 'Powerful transformation during full moon.'),
('Minks'' Sulong Form', 'Enhanced Combat Abilities', 'Unleashes incredible speed and strength.');


-- Create table for Seastone
CREATE TABLE seastone (
    id NUMBER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    power VARCHAR2(50) NOT NULL,
    description VARCHAR2(255)
);

-- Insert data into Seastone table
INSERT INTO seastone (power, description) VALUES 
('Seastone', 'Nullifies Devil Fruit powers, used in weapons and restraints.'),
('Seastone', 'Weapon Enhancement', 'Grants weapons anti-Devil Fruit properties.');

-- Create table for Weapons and Tools
CREATE TABLE weapons_tools (
    id NUMBER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    power VARCHAR2(50) NOT NULL,
    subpower VARCHAR2(50),
    description VARCHAR2(255)
);

-- Insert data into Weapons and Tools table
INSERT INTO weapons_tools (power, subpower, description) VALUES 
('Weapons and Tools', 'Meito', 'Legendary swords with extraordinary power.'),
('Weapons and Tools', 'Cursed Blades', 'Swords with curses but great power.'),
('Weapons and Tools', 'Santoryu', 'Three-Sword Style used by Zoro.'),
('Weapons and Tools', 'Ryou', 'Advanced Armament Haki.'),
('Weapons and Tools', 'Black Blade', 'Sword permanently coated in Haki.');
('Weapons and Tools', 'Pluton', 'Ancient warship with destructive capabilities.'),
('Weapons and Tools', 'Poseidon', 'Control and communicate with Sea Kings.'),
('Weapons and Tools', 'Uranus', 'Mysterious ancient weapon related to the sky.'),
('Weapons and Tools', 'Ancient Weapon Components', 'Relics used to construct ancient weapons.');


-- Create table for Race-Specific Powers
CREATE TABLE race_specific_powers (
    id NUMBER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    power VARCHAR2(50) NOT NULL,
    description VARCHAR2(255)
);

-- Insert data into Race-Specific Powers table
INSERT INTO race_specific_powers (power, description) VALUES 
('Fish-Men/Merfolk', 'Can breathe underwater and swim at high speeds.'),
('Fish-Men/Merfolk', 'Possess incredible physical strength, especially underwater.'),
('Fish-Men/Merfolk', 'Can communicate with sea creatures using specific sounds.'),
('Fish-Men/Merfolk', 'Capable of performing Fish-Man Karate for devastating water-based attacks.'),
('Fish-Men/Merfolk', 'Able to manipulate water currents for powerful strikes.'),
('Minks', 'Can generate electricity using Electro.'),
('Minks', 'Exhibit heightened physical capabilities under normal conditions.'),
('Minks', 'Can transform into Sulong form under the full moon, greatly amplifying their combat abilities.'),
('Minks', 'Possess sharp claws and enhanced agility.'),
('Minks', 'Extremely skilled in hand-to-hand combat and swordsmanship.'),
('Lunarians', 'Generate fire and possess extreme durability.'),
('Lunarians', 'Can create flames on their back, which they can control for offense or defense.'),
('Lunarians', 'Have immense physical strength and resilience to most physical and elemental attacks.'),
('Lunarians', 'Survive in any harsh environment, including extreme heat or cold.'),
('Oni', 'Known for great physical power.'),
('Oni', 'Possess enhanced durability and natural fighting instincts.'),
('Oni', 'Capable of wielding massive weapons with ease.'),
('Oni', 'Have an innate ability to dominate in battle through sheer brute force.'),
('Skypieans', 'Possess small wings on their back and use Dial technology for combat and travel.'),
('Skypieans', 'Able to produce Milky Dials to create paths in the sky.'),
('Shandians', 'Exceptional warriors with great combat skills, especially with spears and Dial weapons.'),
('Birkans', 'Skilled engineers who utilize advanced technology, such as automata.'),
('Giants', 'Massive size gives them extraordinary physical strength.'),
('Giants', 'Have exceptional stamina and resilience in battle.'),
('Giants', 'Capable of using massive weapons that no other race can wield.'),
('Giants', 'Longevity allows them to live for hundreds of years.'),
('Dwarves (Tontattas)', 'Incredibly fast and agile, despite their small size.'),
('Dwarves (Tontattas)', 'Possess surprising strength relative to their size.'),
('Dwarves (Tontattas)', 'Skilled at cultivating and harvesting rare plants.'),
('Dwarves (Tontattas)', 'Naturally stealthy, making them excellent spies.'),
('Kaidou’s Beasts', 'Some Oni-like races possess the ability to transform into hybrid or animal forms.'),
('Three-Eyed Tribe', 'When awakened, they can hear the Voice of All Things and interpret Poneglyphs.'),
('Three-Eyed Tribe', 'Possess heightened intelligence and observation abilities.'),
('Longarm Tribe', 'Have elongated arms with additional joints, enhancing their reach in combat.'),
('Longarm Tribe', 'Possess significant physical strength and flexibility.'),
('Longleg Tribe', 'Have exceptionally long legs, giving them powerful kicks and enhanced mobility.'),
('Longleg Tribe', 'Skilled in leg-based combat techniques.'),
('Snakenecks', 'Possess long, flexible necks for unique combat and movement strategies.'),
('Snakenecks', 'Enhanced vision and reaction speed due to their unique anatomy.'),
('Wotans', 'Hybrid offspring of Fish-Men and Giants, combining both races’ immense strength and underwater abilities.'),
('Kumate Tribe', 'Savage warriors skilled in ambush tactics and tribal combat styles.'),
('Humans', 'Break the fourth wall with unique awareness, often attributed to plot significance.'),
('Humans', 'Prophecy bearers whose predictions often manifest as truth.');


-- Create table for Ancient Weapons
CREATE TABLE ancient_weapons (
    id NUMBER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    power VARCHAR2(50) NOT NULL,
    description VARCHAR2(255)
);

-- Insert data into Ancient Weapons table
INSERT INTO ancient_weapons (power, description) VALUES 
('Pluton', 'Ancient warship with destructive capabilities.'),
('Poseidon', 'Control and communicate with Sea Kings.'),
('Uranus', 'Mysterious ancient weapon related to the sky.');

-- Create table for Voice of All Things
CREATE TABLE voice_of_all_things (
    id NUMBER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    power VARCHAR2(50) NOT NULL,
    description VARCHAR2(255)
);

-- Insert data into Voice of All Things table
INSERT INTO voice_of_all_things (power, description) VALUES 
('Voice of All Things', 'Ability to hear the voice of living creatures and objects.'),
('Voice of All Things', 'Ancient Language Interpretation', 'Allows understanding of Poneglyphs.');


COMMIT;


-- See Tables
SELECT * FROM devil_fruits;
SELECT * FROM haki;
SELECT * FROM martial_arts;
SELECT * FROM weather_control;
SELECT * FROM rokushiki;
SELECT * FROM weapons_tools;
SELECT * FROM cyborg_modifications;
SELECT * FROM giant_strength;
SELECT * FROM vinsmoke_germa;
SELECT * FROM minks_sulong;
SELECT * FROM seastone;
SELECT * FROM ancient_weapons;
SELECT * FROM voice_of_all_things;